name: 'code review'
on: # rebuild any PRs and main branch changes
  pull_request:
    types:
      - labeled
permissions:
  contents: read
  pull-requests: write
jobs:
  code-review: # make sure the action works on a clean machine without building
    if: ${{ contains( github.event.label.name, 'AUTO') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        env:
          NODE_OPTIONS: '--experimental-fetch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model_temperature: 0
          model_name: 'claude-3-5-sonnet-20241022'
          exclude_files: '*.js, *.json, *.md, *.yml, *.js.map, .node-version'
