name: 'Code Review'

on:
  push:

jobs:
  code-review: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest

    steps:
      - uses: arpitgandhi9/creview@v0.3
        env:
          NODE_OPTIONS: '--experimental-fetch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model_temperature: 0
          model_name: 'claude-3-5-sonnet-20241022'
          exclude_files: '*.js, *.json, *.md, *.yml, *.js.map, .node-version'
